### ISSUE TITLE
After your tests, which database would you recommend?

### ISSUE THREAD

**Issue by psclkhoury** [bytefish/GermanWeatherDataExample#1]
Great series, I was considering the same thing and stumbled on your articles.

After having done the tests and played around with TimescaleDb and influxdb, which one would you recommend?

Thanks.

**Comment by bytefish** [comment]
First of all thanks. 

Please note: There are some TODOs in the README. I had some benchmark results and conclusion in there, but the figures were next to useless because my data parsing was too slow... and the databases were not the limiting factor.

I am by no means an authority and my experience is limited to these experiments. See I am biased. I didn't really feel comfortable with InfluxQL, maybe I *just don't get it*. Postgres is a mature database, I can stay in SQL and join with other relational data... and Postgres comes with a lot of tools, like a good query planner for getting hints.

If I would start a project I would go with TimscaleDB.
